ALTER TABLE "FlightOffer" ADD COLUMN "cabinBaggageKg" INTEGER NOT NULL DEFAULT 7;
ALTER TABLE "FlightOffer" ADD COLUMN "cabinBaggagePieces" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "FlightOffer" ADD COLUMN "checkInBaggageKg" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "FlightOffer" ADD COLUMN "checkInBaggagePieces" INTEGER NOT NULL DEFAULT 1;